### ISSUE TITLE
Hmm?

### ISSUE THREAD

**Issue by Udyz** [AlaBouali/bane#3]
[root@vps58608 bane]# python
Python 2.7.5 (default, Apr  2 2020, 13:16:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bane/__init__.py", line 20, in <module>
    from bane.info_s import *
  File "bane/info_s.py", line 6, in <module>
    import dns.resolver
  File "/usr/lib/python2.7/site-packages/dns/resolver.py", line 32, in <module>
    import dns.flags
  File "/usr/lib/python2.7/site-packages/dns/flags.py", line 20, in <module>
    import enum
  File "/usr/lib/python2.7/site-packages/dns/enum.py", line 26
    raise ValueError(f"{name} must be between >= 0 and <= {max}")
                                                               ^
SyntaxError: invalid syntax

**Comment by AlaBouali** [comment]
this error was caused by the dnspython module which is known to cause these kind of issues, please check the solutions here:

https://stackoverflow.com/questions/21641696/python-dns-module-import-error
