### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Switch1024** [AlaBouali/bane#4]
**Traceback (most recent call last):
  File "C:\Users\144919\Desktop\jin.py", line 1, in <module>
    import bane
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\bane\__init__.py", line 17, in <module>
    from bane.ddos import *
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\bane\ddos.py", line 20, in <module>
    from kamene.all import *
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\kamene\all.py", line 16, in <module>
    from .arch import *
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\kamene\arch\__init__.py", line 95, in <module>
    from .windows import *
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\kamene\arch\windows\__init__.py", line 212, in <module>
    ifaces.load_from_powershell()
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\kamene\arch\windows\__init__.py", line 163, in load_from_powershell
    for i in get_windows_if_list():
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\site-packages\kamene\arch\windows\__init__.py", line 77, in get_windows_if_list
    ps = sp.Popen(['powershell', '-NoProfile', 'Get-WMIObject -class Win32_NetworkAdapter', '|', 'select Name, @{Name="InterfaceIndex";Expression={$_.InterfaceIndex}}, @{Name="InterfaceDescription";Expression={$_.Description}},@{Name="InterfaceGuid";Expression={$_.GUID}}, @{Name="MacAddress";Expression={$_.MacAddress.Replace(":","-")}} | where InterfaceGuid -ne $null', '|', 'fl'], stdout = sp.PIPE, universal_newlines = True)
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\144919\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified**

**Comment by AlaBouali** [comment]
#for windows you need to download: winpcap: http://www.win10pcap.org/download/

**Comment by AlaBouali** [comment]
This is caused by something beyond my module:

https://github.com/phaethon/kamene/issues/67
